version: "3"

services:
  alertmanager:
    container_name: alertmanager
    hostname: alertmanager
    image: prom/alertmanager:latest
    ports:
      - 9093:9093
    volumes:
      #  ./containers:/ # TODO?
      - ./containers/etc/alertmanager:/etc/alertmanager
    command:
      - "--config.file=/etc/alertmanager/pagerduty/config.yml"
      - "--storage.path=/alertmanager"

  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus:latest
    depends_on:
      - alertmanager
    links:
      - alertmanager:alertmanager
    ports:
      - 9090:9090
    volumes:
      # - ./containers:/ # TODO?
      - ./containers/etc/prometheus:/etc/prometheus
      - ./data/prometheus:/prometheus
    command:
      - "--config.file=/etc/prometheus/windows.config.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--storage.tsdb.retention.time=200h"
      - "--web.enable-lifecycle"

  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      # - ./containers:/ # TODO?
      - ./containers/etc/grafana:/etc/grafana
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=${GF_USERS_ALLOW_SIGN_UP}
