{
 "title": "Docker Service",
 "tags": [ "docker" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Health checks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "engine_daemon_health_checks_total",
     "legendFormat": "total"
    },
    {
     "expr": "engine_daemon_health_checks_failed_total",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "Container States",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{state=\"stopped\"}",
     "legendFormat": "stopped"
    },
    {
     "expr": "engine_daemon_container_states_containers{state=\"paused\"}",
     "legendFormat": "paused"
    },
    {
     "expr": "engine_daemon_container_states_containers{state=\"running\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Network Actions /s",
   "type": "heatmap",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "engine_daemon_network_actions_seconds_bucket",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}